# yaml-language-server: $schema=https://raw.githubusercontent.com/the-database/traiNNer-redux/refs/heads/master/schemas/redux-config.schema.json
name: 2x_ParagonSR2_Nano_Pretrain
scale: 2
use_amp: true
amp_bf16: false
use_channels_last: true
fast_matmul: true
num_gpu: auto

# -------------------------------------------------------------------------------------------------
# Data
# -------------------------------------------------------------------------------------------------
datasets:
  train:
    name: Train_Dataset
    type: pairedimagedataset
    dataroot_gt: /home/phips/Documents/dataset/cc0/hr
    dataroot_lq: /home/phips/Documents/dataset/cc0/lr_x2
    lq_size: 64
    use_hflip: true
    use_rot: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    accum_iter: 1

  val:
    name: Val_Dataset
    type: pairedimagedataset
    dataroot_gt: /home/phips/Documents/dataset/cc0/val_hr
    dataroot_lq: /home/phips/Documents/dataset/cc0/val_lr_x2

# -------------------------------------------------------------------------------------------------
# Network
# -------------------------------------------------------------------------------------------------
network_g:
  type: paragonsr2_nano

# -------------------------------------------------------------------------------------------------
# Paths
# -------------------------------------------------------------------------------------------------
path:
  pretrain_network_g: ~ # Training from scratch
  strict_load_g: true
  resume_state: ~

# -------------------------------------------------------------------------------------------------
# Training
# -------------------------------------------------------------------------------------------------
train:
  ema_decay: 0.999
  grad_clip: true

  optim_g:
    type: AdamW
    lr: !!float 1.5e-4
    weight_decay: 0.0
    betas: [0.9, 0.99]

  scheduler:
    # Smooth single-cycle cosine decay for a clean TensorBoard curve (no restarts):
    # lr_max -> lr_min over total_iter, stable PSNR/SSIM-oriented pretrain.
    type: CosineAnnealingLR
    T_max: 200000
    eta_min: !!float 1e-7

  total_iter: 200000
  warmup_iter: 2000

  # ---
  # Losses: PSNR/SSIM-oriented pretrain (no perceptual/GAN/contrastive)
  # ---
  losses:
    - type: l1loss
      loss_weight: 1.0
    - type: mssimloss
      loss_weight: 0.1

# -------------------------------------------------------------------------------------------------
# Validation
# -------------------------------------------------------------------------------------------------
val:
  val_enabled: true
  val_freq: 1000
  save_img: false

  metrics_enabled: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: false

# -------------------------------------------------------------------------------------------------
# Logging
# -------------------------------------------------------------------------------------------------
logger:
  print_freq: 100
  save_checkpoint_freq: 5000
  save_checkpoint_format: safetensors
  use_tb_logger: true
