# yaml-language-server: $schema=https://raw.githubusercontent.com/the-database/traiNNer-redux/refs/heads/master/schemas/redux-config.schema.json
# Stage 1 (Clean): ParagonSR2 Nano 2x Fidelity Pretrain - Anti-Ringing Variant
# - Uses MagicKernelSharp2021Upsample with configurable alpha in the architecture (set there).
# - Losses are chosen to:
#     * Keep strong fidelity (L1).
#     * Gently suppress ringing/ghost edges (FF + tiny TV).
# - No perceptual, no GAN, no MSSIM here.
# - Goal: artifact-minimized, sharp, neutral backbone for subsequent perceptual finetune.

name: 2x_ParagonSR2_Nano_Pretrain_Clean
scale: 2

use_amp: true
amp_bf16: false
use_channels_last: true
fast_matmul: true
num_gpu: auto

# -------------------------------------------------------------------------------------------------
# Data
# -------------------------------------------------------------------------------------------------
datasets:
  train:
    name: Train_Dataset
    type: pairedimagedataset
    dataroot_gt: /home/phips/Documents/dataset/cc0/hr
    dataroot_lq: /home/phips/Documents/dataset/cc0/lr_x2
    lq_size: 256
    use_hflip: true
    use_rot: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    accum_iter: 1

  val:
    name: Val_Dataset
    type: pairedimagedataset
    dataroot_gt: /home/phips/Documents/dataset/cc0/val_hr
    dataroot_lq: /home/phips/Documents/dataset/cc0/val_lr_x2

# -------------------------------------------------------------------------------------------------
# Network
# -------------------------------------------------------------------------------------------------
network_g:
  type: paragonsr2_nano
  # Controls MagicKernelSharp2021Upsample sharpening strength inside the arch.
  # Must be read by paragonsr2_nano and passed into MagicKernelSharp2021Upsample.
  # For this clean pretrain we use a conservative value.
  upsampler_alpha: 0.5

# No discriminator for fidelity pretrain
# network_d: omitted

# -------------------------------------------------------------------------------------------------
# Paths
# -------------------------------------------------------------------------------------------------
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# -------------------------------------------------------------------------------------------------
# Training
# -------------------------------------------------------------------------------------------------
train:
  ema_decay: 0.995          # Optional EMA for stability; visually validate before using for export.
  grad_clip: true

  optim_g:
    type: AdamW
    lr: !!float 1.5e-4
    weight_decay: 0.0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100000, 160000]
    gamma: 0.5

  total_iter: 200000
  warmup_iter: 2000

  # ---
  # Losses: Artifact-minimized fidelity stack
  # ---
  losses:
    - type: l1loss
      loss_weight: 1.0

    # Gentle frequency regularization:
    # Helps discourage oscillatory ringing while preserving real high-frequency detail.
    - type: ffloss
      loss_weight: 0.05

    # Tiny TV loss:
    # Penalizes rapid sign-flipping gradients (ringing/speckle) at very low strength.
    - type: tvloss
      loss_weight: 0.01

# -------------------------------------------------------------------------------------------------
# Validation
# -------------------------------------------------------------------------------------------------
val:
  val_enabled: true
  val_freq: 5000
  save_img: true

  metrics_enabled: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: false

# -------------------------------------------------------------------------------------------------
# Logging
# -------------------------------------------------------------------------------------------------
logger:
  print_freq: 100
  save_checkpoint_freq: 5000
  save_checkpoint_format: safetensors
  use_tb_logger: true
