# yaml-language-server: $schema=https://raw.githubusercontent.com/the-database/traiNNer-redux/refs/heads/master/schemas/redux-config.schema.json
name: 2x_ParagonSR2_Tiny_Perceptual
scale: 2
use_amp: true
amp_bf16: false
use_channels_last: true
fast_matmul: true
num_gpu: auto

# -------------------------------------------------------------------------------------------------
# Data
# -------------------------------------------------------------------------------------------------
datasets:
  train:
    name: Train_Dataset
    type: pairedimagedataset
    dataroot_gt: /home/phips/Documents/dataset/cc0/hr
    dataroot_lq: /home/phips/Documents/dataset/cc0/lr_x2
    lq_size: 64
    use_hflip: true
    use_rot: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    accum_iter: 1

  val:
    name: Val_Dataset
    type: pairedimagedataset
    dataroot_gt: /home/phips/Documents/dataset/cc0/val_hr
    dataroot_lq: /home/phips/Documents/dataset/cc0/val_lr_x2

# -------------------------------------------------------------------------------------------------
# Network
# -------------------------------------------------------------------------------------------------
network_g:
  type: paragonsr2_tiny

network_d:
  type: dunet

# -------------------------------------------------------------------------------------------------
# Paths
# -------------------------------------------------------------------------------------------------
path:
  pretrain_network_g: ~ # Training from scratch
  strict_load_g: true
  resume_state: ~

# -------------------------------------------------------------------------------------------------
# Training
# -------------------------------------------------------------------------------------------------
train:
  ema_decay: 0.999
  grad_clip: true

  optim_g:
    type: AdamW
    lr: !!float 2e-4 # Higher LR for training from scratch
    weight_decay: 0.0
    betas: [0.9, 0.99]
  optim_d:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingWarmRestarts
    T_0: 250000
    eta_min: !!float 1e-7

  total_iter: 250000
  warmup_iter: 2000

  # ---
  # Losses: Curated for excellent perceptual quality from a small model
  # ---
  losses:
    # Foundational Fidelity & Structure
    - type: l1loss
      loss_weight: 1.0
    - type: mssimloss
      loss_weight: 1.0

    # Perceptual & Realism
    - type: perceptualloss
      criterion: l1
      loss_weight: 0.5
      layer_weights:
        'conv4_4': 1
    - type: distsloss
      loss_weight: 0.5
    - type: ContrastiveLoss
      loss_weight: 0.3
      temperature: 0.1

    # Color & Detail
    - type: hsluvloss
      loss_weight: 0.5
    - type: ffloss
      loss_weight: 0.25

    # Adversarial (Subtle)
    - type: ganloss
      gan_type: r3gan
      loss_weight: 0.05
      r1_weight: 3.0
      r2_weight: 3.0

# -------------------------------------------------------------------------------------------------
# Validation
# -------------------------------------------------------------------------------------------------
val:
  val_enabled: true
  val_freq: 2500
  save_img: true

  metrics_enabled: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: false
    lpips:
      type: calculate_lpips
      better: lower
    dists:
      type: calculate_dists
      better: lower
    topiq:
      type: calculate_topiq

# -------------------------------------------------------------------------------------------------
# Logging
# -------------------------------------------------------------------------------------------------
logger:
  print_freq: 100
  save_checkpoint_freq: 2500
  save_checkpoint_format: safetensors
  use_tb_logger: true
