# yaml-language-server: $schema=https://raw.githubusercontent.com/the-database/traiNNer-redux/refs/heads/master/schemas/redux-config.schema.json
#########################################################################################
# ParagonSR2 S - Real-World Degradations (Complex, Multiple Artifacts)
# Handles blur, noise, JPG/AVIF/WebP compression, downsampling artifacts
# Requires discriminator for photorealistic output quality
#########################################################################################
name: 2xParagonSR2_S_Real
scale: 2

use_amp: true
amp_bf16: true
use_channels_last: true
fast_matmul: true
num_gpu: auto

datasets:
  train:
    name: Train
    type: pairedimagedataset
    dataroot_gt: /home/phips/Documents/dataset/cc0/hr
    dataroot_lq: /home/phips/Documents/dataset/cc0/lr_x2_real # Complex degradations
    lq_size: 128
    use_hflip: true
    use_rot: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 4
    accum_iter: 1

  val:
    name: Val
    type: pairedimagedataset
    dataroot_gt: /home/phips/Documents/dataset/cc0/val_hr
    dataroot_lq: /home/phips/Documents/dataset/cc0/val_lr_x2_real

network_g:
  type: paragonsr2_s

network_d:
  type: munet # Multi-branch discriminator for artifact detection

path:
  # Start from fidelity or perceptual pretrain
  pretrain_network_g: experiments/2xParagonSR2_S_Perceptual/models/net_g_ema_60000.safetensors
  strict_load_g: true
  resume_state: ~

train:
  ema_decay: 0.995 # Lower for diverse degradations
  ema_power: 0.75
  grad_clip: true

  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.99]

  optim_d:
    type: AdamW
    lr: !!float 3e-5 # Conservative discriminator LR
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [30000, 45000]
    gamma: 0.5

  total_iter: 60000
  warmup_iter: 200

  # Comprehensive loss stack for real-world degradations
  losses:
    # 1. Pixel accuracy - ramp down aggressively
    - type: charbonnierloss
      loss_weight: 0.8
      target_iter: 25000
      target_weight: 0.08 # Very low for photorealism
      schedule_type: linear

    # 2. Perceptual - core structure preservation
    - type: convnextperceptualloss
      loss_weight: 0.5
      layers: [1, 2]
      layer_weights: [1.0, 0.7]

    # 3. Texture quality
    - type: distsloss
      loss_weight: 0.1

    # 4. Feature matching - align with discriminator
    - type: featurematchingloss
      loss_weight: 0.5
      layers: ["down2", "mid"]
      criterion: charbonnier

    # 5. LDL - local artifact removal (critical for real degradations)
    - type: ldlloss
      loss_weight: 10.0

    # 6. Color stability
    - type: ConsistencyLoss
      loss_weight: 0.25
      criterion: "chc"
      blur: false
      brightness: 1.0
      saturation: 1.0
      cosim: true
      cosim_weight: 0.5

    # 7. Frequency domain - handles compression artifacts
    - type: ffloss
      loss_weight: 0.1
      start_iter: 5000
      target_iter: 25000
      target_weight: 0.25 # Higher for compression
      schedule_type: linear

    # 8. Block artifact removal (JPG/WebP/AVIF)
    - type: AdaptiveBlockTVLoss
      loss_weight: 0.005
      block_size: 8
      sharpness: 4.0

    # 9. Edge preservation - critical for blur handling
    - type: hfenloss
      loss_weight: 0.015
      start_iter: 2000
      kernel_size: 7
      sigma: 1.0
      criterion: charbonnier

    # 10. GAN - photorealistic texture synthesis
    - type: ganloss
      gan_type: r3gan
      loss_weight: 0.0001
      start_iter: 10000
      target_iter: 25000
      target_weight: 0.03 # Conservative
      r1_weight: 1.0
      r2_weight: 0.0 # Disabled for speed
      schedule_type: linear

val:
  val_enabled: true
  val_freq: 2500
  save_img: true

  metrics_enabled: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
    ssim:
      type: calculate_ssim
      crop_border: 2
    lpips:
      type: calculate_lpips
      better: lower
    dists:
      type: calculate_dists
      better: lower
    topiq:
      type: calculate_topiq

logger:
  print_freq: 50
  save_checkpoint_freq: 2500
  save_checkpoint_format: safetensors
  use_tb_logger: true
