# yaml-language-server: $schema=https://raw.githubusercontent.com/the-database/traiNNer-redux/refs/heads/master/schemas/redux-config.schema.json
#########################################################################################
# ParagonSR2 S - Video Compression Artifact Removal
# Optimized for YouTube/Netflix compression artifacts
#########################################################################################
name: 2xParagonSR2_S_Video
scale: 2

use_amp: true
amp_bf16: true
use_channels_last: true
fast_matmul: true
num_gpu: auto

datasets:
  train:
    name: Train
    type: pairedimagedataset
    dataroot_gt: /home/phips/Documents/dataset/cc0/hr
    dataroot_lq: /home/phips/Documents/dataset/cc0/lr_x2_video # Video compressed LR
    lq_size: 256 # S model benefits from larger patches
    use_hflip: true
    use_rot: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 4
    accum_iter: 1

  val:
    name: Val
    type: pairedimagedataset
    dataroot_gt: /home/phips/Documents/dataset/cc0/val_hr
    dataroot_lq: /home/phips/Documents/dataset/cc0/val_lr_x2_video

network_g:
  type: paragonsr2_s

path:
  # Load perceptual pretrain
  pretrain_network_g: experiments/2xParagonSR2_S_Perceptual/models/net_g_ema_60000.safetensors
  strict_load_g: true
  resume_state: ~

train:
  ema_decay: 0.999
  ema_power: 0.75
  grad_clip: true

  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [20000, 35000]
    gamma: 0.5

  total_iter: 50000
  warmup_iter: 200

  losses:
    # Pixel accuracy - ramp down for perceptual dominance
    - type: charbonnierloss
      loss_weight: 1.0
      target_iter: 25000
      target_weight: 0.12 # S model (lower than Nano's 0.15)
      schedule_type: linear

    # Perceptual - main driver for natural textures
    - type: convnextperceptualloss
      loss_weight: 0.25 # S model (lower than Nano's 0.5)
      layers: [1, 2]
      layer_weights: [1.0, 0.7]

    # Texture quality
    - type: distsloss
      loss_weight: 0.1

    # Color stability - CRITICAL for video temporal consistency
    - type: ConsistencyLoss
      loss_weight: 0.15 # Higher for video stability
      criterion: "chc"
      blur: false
      cosim: true
      cosim_weight: 0.5

    # Block artifact removal - essential for H.264/H.265
    - type: AdaptiveBlockTVLoss
      loss_weight: 0.012 # S model (lower than Nano's 0.015, more precise)
      block_size: 8 # H.264 8x8 DCT blocks
      sharpness: 4.0

    # Frequency domain - ESSENTIAL for compression artifacts
    - type: ffloss
      loss_weight: 0.1
      start_iter: 2500 # Delay start
      target_iter: 20000
      target_weight: 0.25 # Ramp up for compression artifacts
      schedule_type: linear

    # High-frequency detail preservation
    - type: hfenloss
      loss_weight: 0.1 # S model (higher than Nano, can handle detail)
      start_iter: 2000
      kernel_size: 7
      sigma: 1.0
      criterion: charbonnier

val:
  val_enabled: true
  val_freq: 2500
  save_img: true

  metrics_enabled: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
    ssim:
      type: calculate_ssim
      crop_border: 2
    lpips:
      type: calculate_lpips
      better: lower
    dists:
      type: calculate_dists
      better: lower
    topiq:
      type: calculate_topiq

logger:
  print_freq: 50
  save_checkpoint_freq: 2500
  save_checkpoint_format: safetensors
  use_tb_logger: true
