name: 2xParagonSR2_Micro_DeJPEG_Stream
scale: 2
use_amp: true
amp_bf16: true
use_channels_last: true
fast_matmul: true
num_gpu: auto

datasets:
  train:
    name: Train_Dataset
    type: pairedimagedataset
    # POINT THIS TO YOUR JPEG-DEGRADED DATASET
    dataroot_gt: /home/phips/Documents/dataset/cc0/hr
    dataroot_lq: /home/phips/Documents/dataset/cc0/lr_x2_jpg  # <--- NEW FOLDER
    lq_size: 128
    use_hflip: true
    use_rot: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    accum_iter: 1

  val:
    name: Val_Dataset
    type: pairedimagedataset
    dataroot_gt: /home/phips/Documents/dataset/cc0/val_hr
    # POINT THIS TO JPEG VAL IMAGES TO SEE REAL PROGRESS
    dataroot_lq: /home/phips/Documents/dataset/cc0/val_lr_x2_jpg

network_g:
  type: paragonsr2_static_micro
  hr_blocks: 1

network_d:
  type: munet

path:
  # RESUME FROM YOUR FINISHED PERCEPTUAL MODEL
  pretrain_network_g: experiments/2xParagonSR2_Micro_hrblock_with_FeatureMatching_Optimized/models/net_g_ema_140000.safetensors
  strict_load_g: true
  resume_state: ~

train:
  ema_decay: 0.995
  ema_power: 0.75
  grad_clip: true

  optim_g:
    type: AdamW
    lr: !!float 5e-5      # LOWER LR (Fine-tuning)
    weight_decay: !!float 1.0e-4
    betas: [0.9, 0.99]

  optim_d:
    type: AdamW
    lr: !!float 5e-5      # Match G
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [30000, 45000] # Short run
    gamma: 0.5

  # SHORT RUN: 50k iterations is enough to learn DeJPEG
  total_iter: 50000
  warmup_iter: 200

  # =========================================================
  # SPEED OPTIMIZED LOSS STACK
  # Removed: DISTS, CLIP/Contrastive, HFEN (Too slow/Unnecessary)
  # Kept: GAN, FeatureMatching, Perceptual, Charbonnier, LDL
  # =========================================================
  losses:
    # Base Pixel Loss
    - type: charbonnierloss
      loss_weight: 1.0
      start_iter: 0
      target_iter: 50000
      target_weight: 0.5
      schedule_type: linear

    # Perceptual (Keep ConvNeXt, it's better than VGG)
    - type: convnextperceptualloss
      loss_weight: 0.5
      start_iter: 0
      layers: [1, 2]
      layer_weights: [1.0, 0.7]

    # GAN Loss (Essential for texture)
    - type: ganloss
      gan_type: r3gan
      loss_weight: 0.05
      start_iter: 0       # Start immediately (we are fine-tuning)
      r1_weight: 0.0      # Speed optimization (using pretrain so should be stable enough)
      r2_weight: 0.0

    # Feature Matching (Stabilizes GAN)
    - type: featurematchingloss
      loss_weight: 0.5
      start_iter: 0       # Start immediately
      layers: [ 'down2', 'mid' ]   # Removed 'down1' for VRAM efficiency
      criterion: charbonnier

    # LDL (CRITICAL for DeJPEG)
    # Prevents the GAN from sharpening JPEG artifacts
    - type: ldlloss
      loss_weight: 0.5
      start_iter: 0

    #- type: distsloss
    #  loss_weight: 0.05
    #  start_iter: 0

    - type: AdaptiveBlockTVLoss
      loss_weight: 0.05
      start_iter: 0
      block_size: 8  # Targets JPEG blocks

val:
  val_enabled: true
  val_freq: 5000
  save_img: true
  metrics_enabled: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
    # Removed LPIPS/DISTS/TOPIQ to speed up validation checks
    # Visual inspection is more important for DeJPEG anyway

logger:
  print_freq: 100
  save_checkpoint_freq: 5000
  save_checkpoint_format: safetensors
  use_tb_logger: true
