# yaml-language-server: $schema=https://raw.githubusercontent.com/the-database/traiNNer-redux/refs/heads/master/schemas/redux-config.schema.json
#########################################################################################
# ParagonSR2 Hybrid Nano - De-JPEG (Light Artifacts Only)
# For Q70-95 JPEG cleanup - Nano struggles with heavier compression
#########################################################################################
name: 2xParagonSR2_Nano_DeJPEG_Light
scale: 2

use_amp: true
amp_bf16: true
use_channels_last: true
fast_matmul: true
num_gpu: auto

datasets:
  train:
    name: Train Dataset
    type: pairedimagedataset
    dataroot_gt: /home/phips/Documents/dataset/cc0/hr
    dataroot_lq: /home/phips/Documents/dataset/cc0/lr_x2_jpg # JPEG degraded
    lq_size: 128
    use_hflip: true
    use_rot: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 10
    accum_iter: 1

  val:
    name: Val Dataset
    type: pairedimagedataset
    dataroot_gt: /home/phips/Documents/dataset/cc0/val_hr
    dataroot_lq: /home/phips/Documents/dataset/cc0/val_lr_x2_jpg

network_g:
  type: paragonsr2_nano
  scale: 2

# No discriminator for Nano - keep it simple and fast
# network_d:
#   type: munet

path:
  # Optionally load from perceptual pretrain
  pretrain_network_g: experiments/2xParagonSR2_Nano_Perceptual/models/net_g_ema_50000.safetensors
  strict_load_g: true
  resume_state: ~

train:
  ema_decay: 0.999
  ema_power: 0.75
  grad_clip: true

  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [20000, 35000]
    gamma: 0.5

  total_iter: 50000
  warmup_iter: 200

  # Simplified de-JPEG loss stack for Nano
  losses:
    # Pixel accuracy - ramp down
    - type: charbonnierloss
      loss_weight: 1.0
      target_iter: 25000
      target_weight: 0.15
      schedule_type: linear

    # Perceptual - keep structures
    - type: convnextperceptualloss
      loss_weight: 0.5
      layers: [1, 2]
      layer_weights: [1.0, 0.7]

    # Texture quality
    - type: distsloss
      loss_weight: 0.1

    # JPEG block artifact removal - critical for de-JPEG
    - type: AdaptiveBlockTVLoss
      loss_weight: 0.01 # Higher than S due to nano's limited capacity
      block_size: 8
      sharpness: 4.0

    # Frequency domain - helps with JPEG artifacts
    - type: ffloss
      loss_weight: 0.1
      start_iter: 2500
      target_iter: 20000
      target_weight: 0.2

val:
  val_enabled: true
  val_freq: 2500
  save_img: true

  metrics_enabled: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
    ssim:
      type: calculate_ssim
      crop_border: 2
    lpips:
      type: calculate_lpips
      better: lower
    dists:
      type: calculate_dists
      better: lower

logger:
  print_freq: 50
  save_checkpoint_freq: 2500
  save_checkpoint_format: safetensors
  use_tb_logger: true
