# yaml-language-server: $schema=https://raw.githubusercontent.com/the-database/traiNNer-redux/refs/heads/master/schemas/redux-config.schema.json
#########################################################################################
# ParagonSR2 Nano - PSISR-D Dataset Comparison
# Dataset: psisrd (moderate complexity dataset)
# Optimized for: Balanced comparison metrics
#########################################################################################
name: 2xParagonSR2_Nano_PSISR_D
scale: 2

use_amp: true
amp_bf16: false
use_channels_last: true
fast_matmul: true
num_gpu: auto
manual_seed: 1024

datasets:
  train:
    name: PSISR_D_Train
    type: pairedimagedataset
    dataroot_gt: /home/phips/Documents/dataset/PDM/OSISRD/v3/hr        # Update path for psisrd
    dataroot_lq: /home/phips/Documents/dataset/PDM/OSISRD/v3/x2     # Update path for psisrd
    lq_size: 128
    use_hflip: true
    use_rot: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 32
    accum_iter: 1

  val:
    name: CC0_147k_Val
    type: pairedimagedataset
    dataroot_gt: /home/phips/Documents/dataset/cc0/val_hr
    dataroot_lq: /home/phips/Documents/dataset/cc0/val_lr_x2_bicubic_aa

network_g:
  type: paragonsr2_nano

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

train:
  ema_decay: 0.999
  ema_power: 0.75
  grad_clip: true

  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [20000, 30000]
    gamma: 0.5

  total_iter: 40000
  warmup_iter: 500

  # Dynamic Loss Scheduling - Balanced for Medium Dataset
  dynamic_loss_scheduling:
    enabled: true
    momentum: 0.9
    adaptation_rate: 0.01
    min_weight: 1e-6
    max_weight: 100.0
    adaptation_threshold: 0.1
    baseline_iterations: 100
    enable_monitoring: true

  losses:
    - type: l1loss
      loss_weight: 1.0
    - type: ssimloss
      loss_weight: 0.05

val:
  val_enabled: true
  val_freq: 1000                      # Every 1000 iterations
  save_img: false                     # Disable for faster validation

  metrics_enabled: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
    ssim:
      type: calculate_ssim
      crop_border: 4

logger:
  print_freq: 100
  save_checkpoint_freq: 20000
  save_checkpoint_format: safetensors
  use_tb_logger: true
