#########################################################################################
# ParagonSR2 Nano Auto-Optimized VRAM Management Config
# For RTX 3060 12GB: lq_size=128, batch=16, workers=8
# For RTX 4090 24GB: lq_size=256, batch=32, workers=8
#########################################################################################
name: 2xParagonSR2_Nano_AUTO_fidelity
scale: 2

# VRAM MANAGEMENT SYSTEM
auto_vram_management:
  enabled: true                    # Enable automatic VRAM management
  target_vram_usage: 0.85         # Target 85% VRAM usage (prevents OOM)
  safety_margin: 0.05             # Additional 5% safety margin

use_amp: true
amp_bf16: true
use_channels_last: true
num_gpu: auto

datasets:
  train:
    name: CC0_147k_Train
    type: pairedimagedataset
    dataroot_gt: /home/phips/Documents/dataset/cc0/filtered_versions/cc0_c5_hr
    dataroot_lq: /home/phips/Documents/dataset/cc0/filtered_versions/cc0_c5_lr_x2

    # OPTIMIZED PARAMETERS for RTX 3060 12GB (Auto-VRAM managed)
    lq_size: 128                   # Safe LR patch size for RTX 3060
    batch_size_per_gpu: 8          # Optimized batch size to prevent OOM
    num_worker_per_gpu: 8          # Workers for efficient data loading
    accum_iter: 1                  # No gradient accumulation needed for Nano

    use_hflip: true
    use_rot: true

  val:
    name: CC0_147k_Val
    type: pairedimagedataset
    dataroot_gt: /home/phips/Documents/dataset/cc0/val_hr
    dataroot_lq: /home/phips/Documents/dataset/cc0/val_lr_x2_bicubic_aa

network_g:
  type: paragonsr2_nano

path:
  pretrain_network_g: ~
  strict_load_g: true

train:
  ema_decay: 0.999
  ema_power: 0.75
  grad_clip: true

  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [40000, 50000, 55000]
    gamma: 0.5

  total_iter: 60000
  warmup_iter: 1000

  # DYNAMIC LOSS SCHEDULING WITH AUTO-CALIBRATION
  dynamic_loss_scheduling:
    enabled: true

  # TRAINING AUTOMATIONS
  training_automations:
    intelligent_learning_rate_scheduler:
      enabled: true

    DynamicBatchSizeOptimizer:
      enabled: true
      target_vram_usage: 0.85
      safety_margin: 0.05
      adjustment_frequency: 100
      min_batch_size: 2
      max_batch_size: 64
      min_lq_size: 32
      max_lq_size: 256
      vram_history_size: 50

    early_stopping:
      enabled: true
      patience: 3000
      min_improvement: 0.0005
      metric: "val/psnr"

    adaptive_gradient_clipping:
      enabled: true

  # OPTIMAL FIDELITY LOSS COMBINATION
  losses:
    - type: l1loss
      loss_weight: 1.0
    - type: mssimloss
      loss_weight: 0.08

val:
  val_enabled: true
  val_freq: 1000
  save_img: true

  metrics_enabled: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
    ssim:
      type: calculate_ssim
      crop_border: 4

logger:
  print_freq: 100
  save_checkpoint_freq: 10000
  save_checkpoint_format: safetensors
  use_tb_logger: true
