#########################################################################################
# ParagonSR2 Nano - CC0 147k Dataset (FIXED CONFIGURATION)
# Fixed: Gradient scaling, dynamic loss scheduling, AMP, LR schedule
#########################################################################################
name: 2xParagonSR2_Nano_BHI
scale: 2

use_amp: true
amp_bf16: true
use_channels_last: true
fast_matmul: true
num_gpu: auto
manual_seed: 1024

datasets:
  train:
    name: CC0_147k_Train
    type: pairedimagedataset
    dataroot_gt: /home/phips/Documents/dataset/BHI/BHI_small/BHI_small
    dataroot_lq: /home/phips/Documents/dataset/BHI/BHI_small/x2
    lq_size: 128
    use_hflip: true
    use_rot: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    accum_iter: 1

  val:
    name: CC0_147k_Val
    type: pairedimagedataset
    dataroot_gt: /home/phips/Documents/dataset/cc0/val_hr
    dataroot_lq: /home/phips/Documents/dataset/cc0/val_lr_x2_bicubic_aa

network_g:
  type: paragonsr2_nano

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

train:
  ema_decay: 0.999
  ema_power: 0.75
  grad_clip: true

  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [30000, 35000]
    gamma: 0.5

  total_iter: 30000
  warmup_iter: 500

  dynamic_loss_scheduling:
    enabled: false # Use fixed loss weights for dataset comparison fairness
    auto_calibrate: false # Detects dataset complexity per dataset, turn off for dataset comparison fairness

  training_automations:
    intelligent_learning_rate_scheduler:
      enabled: false  # Adapts LR per dataset, turn off for dataset comparison fairness
    dynamic_batch_size_optimizer:
      enabled: false  # Changes batch size per dataset, turn off for dataset comparison fairness

  losses:
    - type: l1loss
      loss_weight: 1.0

val:
  val_enabled: true
  val_freq: 1000
  save_img: false

  metrics_enabled: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
    ssim:
      type: calculate_ssim
      crop_border: 4

logger:
  print_freq: 100
  save_checkpoint_freq: 10000
  save_checkpoint_format: safetensors
  use_tb_logger: true
